sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:

  - ghc: 8.6.1
    env: GHCVER='8.6.1' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.6.1
        - cabal-install-head
  
  

install:
  - export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
  - echo $PATH
  - cabal new-update
  - cabal new-build --enable-tests --enable-benchmarks
script:
  - cabal new-test


notifications:
  email: false

